fix `parse()` arguments to match the documented types
opengovsg/pdf2md pull request #77
Opened 2024-01-04 10:37 UTC by moshest

## Problem

_What problem are you trying to solve? What issue does this close?_

The `pdf2md` say it will receive the following type:
```
@param {string|TypedArray|DocumentInitParameters|PDFDataRangeTransport} pdfBuffer
 * Passed to `pdfjs.getDocument()` to read a PDF document for conversion
 ```

However, it only works with `BinaryData` type.

## Solution

_How did you solve the problem?_

I add a type check and make the first argument convert to `docOptions` depends on the type given:

```js
if (typeof docOptions === "string" || docOptions instanceof URL) {
  docOptions = { url: docOptions };
} else if (docOptions instanceof ArrayBuffer || ArrayBuffer.isView(docOptions)) {
  docOptions = { data: docOptions };
}
```

This should match the docs of `pdfjs`:
https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib.html

2024-01-11 02:52 UTC, LoneRifle approved these changes
lgtm

2024-01-11 03:02 UTC, LoneRifle requested changes
Hang on. it's possible for `docOptions` to be a string _but not a URL_, ie, a binary string that represents the PDF blob itself. Could there be a stronger check to validate `docOptions` as something we can actually supply as a `url` to pdfjs?

2024-01-11 13:50 UTC, moshest commented
I don't think we need to be holier than the pope:
https://github.com/mozilla/pdf.js/blob/12875359c387d7e2d312c50748833b3c52d986aa/src/display/api.js#L234

```ts
function getDocument(src) {
   // ...

   if (typeof src === "string" || src instanceof URL) {
      src = { url: src };
    } else if (isArrayBuffer(src)) {
      src = { data: src };
    }

    // ...
}

2024-05-23 00:57 UTC, LoneRifle approved these changes

2024-05-23 00:57 UTC, merged